opensource-f2f/episode

- README.md
> 增加 S01E02 李自：参与开源社区的原动力探索——自我价值的实现和社会认可

- README.md
> Added S01E03 - YiHong

- README.md
> Put RSS URL in README and replace URL in repo description

- README.md
> Fix the wrong link of S01E03 in README.md

- README.md
Hi,
This PR adds Miya's episode :)
> docs: added Miya's episode

- README.md
resolve https://github.com/opensource-f2f/episode/issues/21
resolve https://github.com/opensource-f2f/episode/issues/22
> docs: added Twitter & afdian

- README.md
> 专访 琚[jū]致远：聊聊兴趣与成就感如何驱动他参与开源社区

- .github/FUNDING.yml
> 添加“爱发电”到GitHub仓库

- .github/settings.yml
> Using a YAML file to manage this repo

- shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
close https://github.com/opensource-f2f/episode/issues/54
> 增加 shownotes，S01E01 开发者关系 (DevRel) 是开源项目和开源社区的加速器

- shownotes/S01E02-李自：参与开源社区的原动力探索——自我价值的实现和社会认可.md
> 添加 S01E02 剪辑

- .github/ISSUE_TEMPLATE/recommend_guest.md
> comment notice in issue template

- shownotes/S02E02-走进全员Remote公司StreamNative，共建开源乐园.md
> Add S02E02-走进全员Remote公司StreamNative，共建开源乐园.md in shownotes

- shownotes/S01E05-专访琚[jū]致远：聊聊兴趣与成就感如何驱动他参与开源社区.md
> Add S01E05-专访琚[jū]致远：聊聊兴趣与成就感如何驱动他参与开源社区.md in shownotes

- .github/workflows/orbit.yaml
- activities.yaml
Hold this PR until the meeting finished.
> Add support to record events to Orbit

- shownotes/S01E11-白宦成：开源的魅力在于 show in public.md
Simple updated mikey's personal information
> update mikey's bio

- shownotes/README.md
> 优化 shownotes 的模板

- shownotes/S01E09-开源运营：运营能为开源带来什么.md
> 修改 mikey 的个人地址

- README.tpl
See the screenshot with the changes to this PR.
> Make the host and guest list keeps in alphabetical order

- shownotes/S01E15-嵇斌：近 20 年的 IT 老兵作为开源新人的思考.md
> S01E15-嵇斌：近 20 年的 IT 老兵作为开源新人的思考.md

- archives/LiMeng00.yaml
非常开心看到 @LiMeng00 也从幕后走向台前！加油！！！
> 增加李梦的开源相关的资料链接

- shownotes/S01E16-三咲智子：作为一名学生参与开源社区的故事.md
close https://github.com/opensource-f2f/episode/issues/98
see also https://github.com/opensource-f2f/episode/issues/32
> S01E16 三咲智子：作为一名学生参与开源社区的故事

- README.md
- README.tpl
- shownotes/00-2022元旦：四位主播居然都是“社恐”.md
- shownotes/01-开源许可证在国内等于格式合同.md
- shownotes/02-开源布道师布的是什么道.md
- shownotes/S01E00-开源面对面节目自述.md
- shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
- shownotes/S01E02-李自：参与开源社区的原动力探索——自我价值的实现和社会认可.md
- shownotes/S01E03-专访Yihong-自学成为流行开源项目作者的点滴.md
- shownotes/S01E04-Miya的故事-从工地打印小妹到全球知名教育公益开源社区大使.md
- shownotes/S01E05-专访琚[jū]致远：聊聊兴趣与成就感如何驱动他参与开源社区.md
- shownotes/S01E06-从民营书店进货员到开源创业工程师的故事.md
- shownotes/S01E07-面对开放的大门，技术小白可以怎样开始参与开源.md
- shownotes/S01E08-小雅：我在读研期间参与 CHAOSS 开源社区的心路经历.md
- shownotes/S01E09-开源运营：运营能为开源带来什么.md
- shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
- shownotes/S01E11-白宦成：开源的魅力在于 show in public.md
- shownotes/S01E12-小宇：一名测试工程师探索开源世界的经历.md
- shownotes/S01E13-MINGAI：从同传到创作到运营，机缘巧合入了开源桃花坞.md
- shownotes/S01E14-亮小猪：从开发到管理到开发者关系，他都经历了什么.md
- shownotes/S01E15-嵇斌：近 20 年的 IT 老兵作为开源新人的思考.md
- shownotes/S01E16-三咲智子：作为一名学生参与开源社区的故事.md
- shownotes/S02E01-从商业到开源社区，聊聊JuiceFS的开发者招聘.md
- shownotes/S02E02-走进全员Remote公司StreamNative，共建开源乐园.md
- shownotes/S03E01-iOS 开源项目 IceCream 与其作者蔡越的故事.md
The new metadata structure would be convenient for https://github.com/opensource-f2f/website
See also
> Improve the episode metadata

- shownotes/S01E16-三咲智子：作为一名学生参与开源社区的故事.md
> Fix the wrong number

- archives/linuxsuren.md
- shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
- shownotes/S01E17-Tison：一名 Community Builder 的自白.md
hi @tisonkun , please feel free to help us review this PR. And welcome to add more links about you.
By the way, I need to say a BIG thanks to @wey-gu for helping to invite @tisonkun as our guest.
close https://github.com/opensource-f2f/episode/issues/86
> Tison：一名 Community Builder 的自白

- .github/workflows/generator.yml
- .github/workflows/orbit.yaml
- .github/workflows/update-website.yml
Relate issue https://github.com/opensource-f2f/website/issues/29
> ci: add update website & format

- README.tpl
> Put VLC into the RSS client list

- archives/ichengxinxin.md
hi @ichengxinxin , please help to review this.
> Add a profile of ichengxinxin

- README.tpl
Add the number of classification description.
> Update the season number in the README.tpl

- README.tpl
更新跟开源有关的中英文播客，作者包括企业和个人作品、内容涵盖Linux发行版和编程语言等。
> 更新开源相关的中英文播客

- archives/wey-gu.md
> Create profile for wey-gu

- shownotes/00-2022元旦：四位主播居然都是“社恐”.md
- shownotes/01-开源许可证在国内等于格式合同.md
- shownotes/02-开源布道师布的是什么道.md
- shownotes/S01E00-开源面对面节目自述.md
- shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
- shownotes/S01E02-李自：参与开源社区的原动力探索——自我价值的实现和社会认可.md
- shownotes/S01E03-专访Yihong-自学成为流行开源项目作者的点滴.md
- shownotes/S01E04-Miya的故事-从工地打印小妹到全球知名教育公益开源社区大使.md
- shownotes/S01E05-专访琚[jū]致远：聊聊兴趣与成就感如何驱动他参与开源社区.md
- shownotes/S01E06-从民营书店进货员到开源创业工程师的故事.md
- shownotes/S01E07-面对开放的大门，技术小白可以怎样开始参与开源.md
- shownotes/S01E08-小雅：我在读研期间参与 CHAOSS 开源社区的心路经历.md
- shownotes/S01E09-开源运营：运营能为开源带来什么.md
- shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
- shownotes/S01E11-白宦成：开源的魅力在于 show in public.md
- shownotes/S01E12-小宇：一名测试工程师探索开源世界的经历.md
- shownotes/S01E13-MINGAI：从同传到创作到运营，机缘巧合入了开源桃花坞.md
- shownotes/S01E14-亮小猪：从开发到管理到开发者关系，他都经历了什么.md
- shownotes/S01E15-嵇斌：近 20 年的 IT 老兵作为开源新人的思考.md
- shownotes/S01E16-三咲智子：作为一名学生参与开源社区的故事.md
- shownotes/S01E17-Tison：一名 Community Builder 的自白.md
- shownotes/S01E18 Daniel.md
- shownotes/S02E01-从商业到开源社区，聊聊JuiceFS的开发者招聘.md
- shownotes/S02E02-走进全员Remote公司StreamNative，共建开源乐园.md
- shownotes/S03E01-iOS 开源项目 IceCream 与其作者蔡越的故事.md
- shownotes/S03E02-走近一个面向未来的操作系统FydeOS.md
- shownotes/S03E03-Jina AI 赋能所有开发者，让超酷的多模态 AI 想法实现落地.md
Closed: opensource-f2f/website#51
> refactor: modify listening url from 喜马拉雅 to 声湃

- README.tpl
> add wavpub

- shownotes/S01E19-对话吴炳锡：一个 DBA 老兵眼里的开源与生存.md
> Update S01E19-对话吴炳锡：一个 DBA 老兵眼里的开源与生存.md

- README.tpl
add freeCodeCamp official podcast
> add freeCodeCamp official podcast

- README.tpl
> add Code Comments from Redhat

- shownotes/S04E00-吴晟：开源项目进入 Apache 孵化器意味着什么.md
> Create S04E00-吴晟：开源项目进入 Apache 孵化器意味着什么.md

- shownotes/README.md
- shownotes/S04E00-吴晟：开源项目进入 Apache 孵化器意味着什么.md
This should fix https://github.com/opensource-f2f/website/issues/60 
cc @sxzz 
The template will be parsed by the SSR code, thus we should carefully adjust its format.
> fix site build

- shownotes/S04E00-吴晟：开源项目进入 Apache 孵化器意味着什么.md
as title to fix https://github.com/opensource-f2f/website/issues/60
> remove "...."

- shownotes/README.md
See also https://github.com/opensource-f2f/episode/issues/251
> Add required field `date` into the template

- README.tpl
- donation.md
close https://github.com/opensource-f2f/episode/issues/254
> add donation records

- shownotes/04-技术播客节特别节目：请不要忽视开源中的 Burn out 问题.md
> Create 04-技术播客节特别节目：请不要忽视开源中的 Burn out 问题.md

- README.tpl
> 声湃北京录音间位置变更

- shownotes/S04E03-专访开源编程语言 MoonBit.md
> Create S04E03-专访开源编程语言 MoonBit.md
